from flask import Blueprint, current_app, make_response
from database.db import get_db
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm
import io
from datetime import datetime

report_bp = Blueprint('report', __name__)

@report_bp.route('/report/export')
def export_pdf():
    db = get_db(current_app.config['DATABASE'])

    total_assets = db.execute('SELECT COUNT(*) FROM assets').fetchone()[0]
    total_violations = db.execute('SELECT COUNT(*) FROM violations').fetchone()[0]

    violations = db.execute('''
        SELECT v.similarity, v.detected_at, a.name as asset_name
        FROM violations v
        JOIN assets a ON v.asset_id = a.id
        ORDER BY v.detected_at DESC
    ''').fetchall()

    db.close()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle('title',
        fontSize=22, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#4f46e5'), spaceAfter=6)
    sub_style = ParagraphStyle('sub',
        fontSize=10, fontName='Helvetica',
        textColor=colors.HexColor('#475569'), spaceAfter=20)

    elements.append(Paragraph('SportShield AI', title_style))
    elements.append(Paragraph(f'Violation Report — Generated {datetime.now().strftime("%d %b %Y, %H:%M")}', sub_style))

    # Summary table
    summary_data = [
        ['Metric', 'Value'],
        ['Total Registered Assets', str(total_assets)],
        ['Total Violations Detected', str(total_violations)],
        ['Report Generated', datetime.now().strftime('%d %b %Y %H:%M')],
    ]
    summary_table = Table(summary_data, colWidths=[10*cm, 6*cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4f46e5')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('ROUNDEDCORNERS', [4]),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.5*cm))

    # Violations table
    if violations:
        elements.append(Paragraph('Violation Log', ParagraphStyle('h2',
            fontSize=14, fontName='Helvetica-Bold',
            textColor=colors.HexColor('#0f172a'), spaceAfter=10, spaceBefore=10)))

        vdata = [['Asset Name', 'Similarity', 'Risk Level', 'Detected At']]
        for v in violations:
            sim = v['similarity']
            if sim >= 90:
                risk = 'CRITICAL'
            elif sim >= 70:
                risk = 'HIGH'
            elif sim >= 50:
                risk = 'MEDIUM'
            else:
                risk = 'LOW'
            vdata.append([
                v['asset_name'],
                f"{sim}%",
                risk,
                v['detected_at'][:16]
            ])

        vtable = Table(vdata, colWidths=[6*cm, 3*cm, 3*cm, 5*cm])
        vtable.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e11d48')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#fff1f2'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 7),
        ]))
        elements.append(vtable)

    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph(
        'This report was automatically generated by SportShield AI — Digital Asset Protection System.',
        ParagraphStyle('footer', fontSize=8, textColor=colors.HexColor('#94a3b8'))
    ))

    doc.build(elements)
    buf.seek(0)

    response = make_response(buf.read())
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = \
        f'attachment; filename=sportshield_report_{datetime.now().strftime("%Y%m%d")}.pdf'
    return response